### ISSUE TITLE
feat: support `compile_commands.json` from cmake

### ISSUE THREAD

**Issue by pums974** [fortran-lang/vscode-fortran-support#668] opened 2022-09-16 07:38 UTC
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature Request

Hi, 

Supporting `compile_commands.json` from cmake would simplify the definition of `fortran.linter.compiler`, `fortran.linter.includePath`, `fortran.linter.extraArgs` and `fortran.linter.modOutput` for those who are using cmake.

**Comment by gnikit** [comment] 2022-09-16 11:42
Duplicate of #133

**Closed by gnikit** 2022-09-16 11:42 UTC
Labels: feature-request
