### ISSUE TITLE
bug(syntax): Syntax highlighting is not applied on the function caller

### ISSUE THREAD

**Issue by kohei-noda-qcrg** [fortran-lang/vscode-fortran-support#624] opened 2022-08-18 00:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Thank you for providing us a great extension!

This issue may be the same issue as #401, #478 and #597, but I couldn't determine if this is really the case, so I created the issue.

When I use a function, the syntax highlighing on the function caller is not applied.

Please see a screenshot.

I use [fortls](https://github.com/gnikit/fortls) v2.12.0 as a Fortran language server.

### Screenshots

- The function named func_add on line 7 should be highlighted in the same color as the func_add on line 11.

![highlight](https://user-images.githubusercontent.com/103017367/185263453-d7a42694-c63f-4f62-a92f-c81ead45e2f5.png)

### Code Example

```Fortran
program main
    implicit none
    integer i, j, ans
    i = 1
    j = 2
    print *, i, j
    ans = func_add(i, j)
    print *, ans

contains
    pure function func_add(a, b) result(retval)
        integer, intent(in) :: a, b
        integer :: retval
        retval = a + b
    end function func_add
end program main
```

### Fortran Version (Free/Fixed Form)

Free Form e.g. F90+

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.70.1

### Platform and Architecture

Linux, MacOS, Windows(WSL2, Ubuntu 20.04)

**Comment by gnikit** [comment] 2022-08-18 08:16
That is indeed a duplicate of the issues you have listed. The only way to resolve this ambiguity is with `fortls`'s semantic tokens

Duplicate of #401

**Closed by gnikit** 2022-08-18 08:16 UTC
Labels: syntax-highlight

**Comment by kohei-noda-qcrg** [comment] 2022-08-18 10:07
I see.
Thanks for your reply !
