### ISSUE TITLE
bug(syntax): syntax highlighting when using Fortran keywords as variable names

### ISSUE THREAD

**Issue by plevold** [fortran-lang/vscode-fortran-support#478] opened 2022-05-12 11:47 UTC
**Describe the bug**
Found this problem while browsing some legacy code that contained a variable named "type". The MWE below causes all lines after the `type(i) = 'a'` statement to be colored as if it was a string literal. With `type(i) = 'a'` commented out and `x(i) = 'a'` active the syntax highlighting appears correct

**To Reproduce**
Paste code below into editor

**Code sample**
```fortran
subroutine sub()
    implicit none
    character :: type(5)
    character :: x(5)
    integer :: i

    i = 1
    ! x(i) = 'a'
    type(i) = 'a'
    call foo()
end subroutine
```

**Screenshots**
Unexpected behaviour:
![image](https://user-images.githubusercontent.com/10157556/168067828-24f095d2-3b2f-4ca2-a244-3cb4d5b49c44.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/10157556/168067892-2d25a179-0acb-4bd3-87ef-2eaad23f5d65.png)

**Build info (please complete the following information):**

- OS: Windows 10 / WSL
- Extension Version v3.0.2022050508
- Visual Studio Code Version 1.67.1

**Comment by gnikit** [comment] 2022-05-12 15:23
Thanks @plevold for the report. My spidey sense is telling me that this might be another case of having to use semantics tokens to distinguish between `type(i)` and hence might not be possible to solve with just the TexMate grammar files.

**Comment by plevold** [comment] 2022-05-12 15:45
I am not certain, but I think it has worked correctly in an earlier version. Of course if this happens because of some new feature it's probably worth having this inconvenience to get better functionality for good code. Naming a variable "type" isn't the best idea anyways!

**Comment by gnikit** [comment] 2022-06-02 00:55
Okay small update, this is not a regression. I checked all the relevant commits going back to v2.1.0. I will look for a fix now

**Comment by gnikit** [comment] 2022-06-02 04:07
So basically, this issue falls under the category of "cannot be resolved without breaking the general grammar". The relevant bit of regex is this: 
https://github.com/fortran-lang/vscode-fortran-support/blob/b3a649b11e9b864eeff4c0f699f139ab435aefcf/syntaxes/fortran_free-form.tmLanguage.json#L5047-L5077

Basically, the scope I attached below should not trigger at all, i.e. the `begin` regex should not match anything if we have something like `type(i) =`. However as you can see from the regex, the end condition is handled separately. What that means is that we will have to check for the end condition at the same time as the begin condition, which is not easy (or cheap) to do.

I think this issue is a prime candidate to be resolved by the usage of an enhanced grammar through LSP.

BTW one will have the same issue with `integer`, `real`, etc. if used as variable names of arrays.

**Comment by gnikit** [comment] 2022-08-14 14:55
Duplicate of #401

**Closed by gnikit** 2022-08-14 14:55 UTC
Labels: syntax-highlight
