### ISSUE TITLE
bug: <title>fprettify with --case args does not work

### ISSUE THREAD

**Issue by adam-sim-dev** [fortran-lang/vscode-fortran-support#1051] opened 2024-02-02 12:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have tried the Pre-Release of the extension.

- [X] I have replicated the Issue in the latest Pre-Release

### Description

Using the following setting on Windows with VS code 1.86.0 does not work, the Fortran source file will be empty.

  "fortran.formatting.formatter": "fprettify",
    "fortran.formatting.fprettifyArgs": [
        "-i 2",
        "--enable-decl",
        "--case 2 2 2 2"

### Expected Behaviour

Should format the source file

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.86.0

### Platform and Architecture

Windows

**Comment by gnikit** [comment] 2024-02-02 12:43
Duplicate of https://github.com/fortran-lang/vscode-fortran-support/issues/1007

**Closed by gnikit** 2024-02-02 12:43 UTC
Labels: bug
