### ISSUE TITLE
bug: Unable to install `fortls`, `findent` or `fprettify` via pop-up on macOS

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/vscode-fortran-support#670] opened 2022-09-18 21:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

After a fresh install of the VSCode extension on macOS, the following pop-up is shown, recommending me to install `fortls` when I open an arbitrary Fortran file:

<img width="445" alt="Screen Shot 2022-09-18 at 22 27 38" src="https://user-images.githubusercontent.com/43783196/190926984-c408164a-9f48-438d-9360-88985ddf710d.png">

However, installation fails when I hit "Install":

<img width="446" alt="Screen Shot 2022-09-18 at 22 32 08" src="https://user-images.githubusercontent.com/43783196/190927118-03e71a92-92bf-432e-b242-ad1853855ea8.png">

Installation of `findent` and `fprettify` also doesn't work via their respective pop-ups.

It worked after I installed `fortls` and `fprettify` via `pip3` (either via `venv` or after installing `python3` via `brew`).

### Expected Behaviour

It would be more convenient if the installation button worked. It would be even better if `fortls` and a formatter came directly as part of the extension so one wouldn't need to separately install additional dependencies.

### Version of Modern Fortran

v3.2.0

### Version of Visual Studio Code

v1.71.2, installed via Homebrew

### Platform and Architecture

macOS Monterey (Version 12.6, M1)

**Comment by gnikit** [comment] 2022-09-18 21:15
So what is the log channel error thrown that is stopping the installation from being successful? Can you provide any information to make this issue traceable and reproducible in a system other that yours. The command that is executed by the extension is `python3 -m pip install --user --upgrade fortls`, does that command fail when you execute it in your terminal?

Python dependencies cannot come packaged since we would have to deal with the updating of the dependencies

Also I assume you mean version **v3.2.0** not v3.2.1

**Comment by minhqdao** [comment] 2022-09-18 21:40
How can I see the log channel error?

When I execute the command, I get the following warning:

```
Installing collected packages: fortls
  WARNING: The script fortls is installed in '/Users/minh/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fortls-2.13.0
```

Without the `--user` option, however, it is installed to `/opt/homebrew/lib/python3.10/site-packages`, which somewhat looks better to me. It is also in the PATH.

Via the button, nothing is installed.

Yes, `v3.2.0` it is.

**Comment by gnikit** [comment] 2022-09-18 21:48
> How can I see the log channel error?

So the Log channel is where the Terminal is, but on the `OUTPUT` pane. From the drop down (usually right side) select `Modern Fortran`. That is where extensions print logs, infos, warnings, etc. The prompts are only if we want you to interact with the extension or a catastrophic failure serious warning has occurred that needs user intervention.

> When I execute the command, I get the following warning:

That would make sense for `fortls` not being picked up since it's not in your PATH, but from what you are saying this button fails in some other way. I will wait until you post the logs to see what is going on. 

Also don't spend too much time on this. We have already changed the way external dependencies are installed via pip. It should make things a lot more transparent to the user, especially in the case where a process fails. I will issue a pre-release for general testing hopefully later today and you can try it then.

**Comment by minhqdao** [comment] 2022-09-18 21:57
Alright. In fact, I had found that tab but wasn't sure because nothing is printed other than a couple of info-level logs, even after installation fails:

<img width="625" alt="Screen Shot 2022-09-18 at 23 55 51" src="https://user-images.githubusercontent.com/43783196/190929520-e7438684-ba8b-49ff-b909-03c322523046.png">

**Comment by gnikit** [comment] 2022-09-18 22:02
Yes indeed that is not very helpful. Let's wait a bit for me to issue the pre-release and you can maybe try again then. I will ping this issue once ready.

**Comment by minhqdao** [comment] 2022-09-18 22:13
Sure, let's do that. 👍

Oh, and when I try to install `findent` or `fprettify`, these are the error logs:

`["ERROR" - 12:04:55 AM] Python package findent failed to install with code: Error: spawnSync pip ENOENT`

and

["ERROR" - 12:09:20 AM] Python package fprettify failed to install with code: Error: spawnSync pip ENOENT

This is also interesting because I can manually install `fprettify` while `findent` cannot be found by `pip3`.

**Comment by awvwgk** [comment] 2022-09-18 22:18
`findent` is currently not available for MacOS/arm64 from PyPI, you can install `findent` from brew instead (https://formulae.brew.sh/formula/findent).

**Comment by gnikit** [comment] 2022-09-18 22:28
> `fortls` is unfortunately not.

Issue tracked here https://github.com/gnikit/fortls/issues/196

> findent is currently not available for MacOS/arm64 from PyPI,

spot on! The underlying issue is the same as packaging `fpm` with pip. We need to find a way to do this through Actions. I was studying a bit yesterday on how CMake does it with `qemu` and `pypa/cibuildwheel` but I couldn't make much sense of their process. I think build tools is not my strong suite...

**Comment by minhqdao** [comment] 2022-09-27 14:44
Yes, the installation of `fprettify` worked:

```
 *  Executing task: python3 -m pip install --user --upgrade fprettify 

Collecting fprettify
  Using cached fprettify-0.3.7-py3-none-any.whl (28 kB)
Requirement already satisfied: configargparse in /opt/homebrew/lib/python3.10/site-packages (from fprettify) (1.5.3)
Installing collected packages: fprettify
  WARNING: The script fprettify is installed in '/Users/minh/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fprettify-0.3.7
 *  Terminal will be reused by tasks, press any key to close it.
 ```

The installation of `findent` via PyPI obviously didn't work because of https://github.com/fortran-lang/vscode-fortran-support/issues/670#issuecomment-1250397649:

```
 *  Executing task: python3 -m pip install --user --upgrade findent 

ERROR: Could not find a version that satisfies the requirement findent (from versions: none)
ERROR: No matching distribution found for findent

 *  The terminal process "/bin/zsh '-c', 'python3 -m pip install --user --upgrade findent'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.
 ```

`fortls` also worked:

``` *  Executing task: python3 -m pip install --user --upgrade fortls 

Collecting fortls
  Using cached fortls-2.13.0-py3-none-any.whl (92 kB)
Requirement already satisfied: json5 in /opt/homebrew/lib/python3.10/site-packages (from fortls) (0.9.10)
Requirement already satisfied: packaging in /opt/homebrew/lib/python3.10/site-packages (from fortls) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/homebrew/lib/python3.10/site-packages (from packaging->fortls) (3.0.9)
Installing collected packages: fortls
  WARNING: The script fortls is installed in '/Users/minh/Library/Python/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fortls-2.13.0
 *  Terminal will be reused by tasks, press any key to close it.
 ```

The plugins worked in VSCode after adding the location to PATH. I'm still gonna use the homebrew versions, though. 😄

**Comment by gnikit** [comment] 2022-09-27 14:46
Great, I will be closing this then. Feel free to comment on the issue if you have any more problems.

**Closed by gnikit** 2022-09-27 14:46 UTC
Labels: info-needed

**Comment by gnikit** [comment] 2022-09-27 14:48
> I'm still gonna use the homebrew versions, though

For fortls I would strongly recommend against it. The server needs to be able to autoupdate something that is not possible with `brew`
